### ISSUE TITLE
The predict.py file failed to run

### ISSUE THREAD

**Issue by will-be-better** [JiayuanWang-JW/YOLOv8-multi-task#1]
I'm sorry, but when I tried to reproduce it,predict.py got an error when "save=True"
error：
IndexError: boolean index did not match indexed array along dimension 0; dimension is 659 but corresponding boolean dimension is 720

What's the problem, please

**Comment by JiayuanWang-JW** [comment]
I have updated the predict.py files. Please update your predict.py to the latest and try again. If there are any errors, please provide more detailed error information and your predict.py content. Then I will help you to solve that.

**Comment by will-be-better** [comment]
Sorry to bother you, but after I tried your updated predict.py file, the above problem still occurred. When the keyword "save=True", the operation gave an error, and when "save=False", it could run smoothly.



When you run this code:

model.predict(source=r 'c :\Users\HP\Desktop\ r-c.jpg ', imgsz=(384,672), device='cpu',name='v4_daytime', save=True, conf=0.25, iou=0.45, show_labels=False)





The error message is as follows:

IndexError: boolean index did not match indexed array along dimension 0;  dimension is 659 but corresponding boolean dimension is 720


Thank you for your kind help

**Comment by JiayuanWang-JW** [comment]
Could you provide complete error information, such as which line of the code returns and get that error? You can submit a screenshot or the whole error information here. Then I will consider that and figure out it. Thanks. 

I did lots of experiments in my service, they are all good. 
![image](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/105391468/ff44d5d3-107b-4a15-bf2f-8116e48de3fc)

**Comment by will-be-better** [comment]
That's my problem, thank you.
[https://github.com/will-be-better/myproblem/blob/main/error.png](url)

**Comment by will-be-better** [comment]
That's my problem, thank you.
https://github.com/will-be-better/myproblem/blob/main/error.png

**Comment by JiayuanWang-JW** [comment]
I reproduced your problem when I used the not (720,1280) size image. I noticed that you used my pre-train model, it is trained on (720,1280) images. If you want to predict your personal image, which has a different resolution, you should train a new model for your personal dataset. Then it should be work. If you want to use my pre-trained model to predict your personal image, this image should be kept the same size as my training size.

**Comment by will-be-better** [comment]
Thank you very much for your guidance. I have found that due to my cognitive problem, I can run smoothly now.Thank you.

**Comment by qingtian787** [comment]
@will-be-better 请问您最后是如何解决尺寸问题的呢，是更改了自己数据集图片大小还是更改了模型

**Comment by yinheyanxian** [comment]
> @will-be-better 请问您最后是如何解决尺寸问题的呢，是更改了自己数据集图片大小还是更改了模型

同问，请问您是怎么解决的，我也出现了这个问题
