### ISSUE TITLE
针对视频推理报错问题及model.predict报错问题

### ISSUE THREAD

**Issue by Pepe12138** [JiayuanWang-JW/YOLOv8-multi-task#105]
你好，目前模型不能支持视频和实时摄像头输入吗，我目前使用如下代码来展示推理后的图片会有如下报错model.predict为None，输入视频和视频流同样如此，请问如果要实现视频推理，需要针对那些地方进行修改？
_import cv2
from ultralytics import YOLO
img_path = "D:/Desktop/222/000682.jpg" 
img = cv2.imread(filename=img_path) 
model = YOLO(model="D:/Progarm_Data/python_project/YOLOv8-multi-task-main/ultralytics/runs/multi/yolopm42/weights/best.pt")
print("model模型信息", model)  
res = model.predict(source=img, device=[0], name='v4_daytime', save=True, conf=0.25, iou=0.45, show_labels=True)
print("res返回值的类型", type(res))  
print("res结果", res) 
annotated_img = res[0].plot()
cv2.imshow(winname="YOLOV8", mat=annotated_img)
cv2.waitKey(delay=10000)
cv2.imwrite(filename="D:/Desktop/222/000610.jpg", img=annotated_img)

输出：
model模型信息 <ultralytics.yolo.engine.model.YOLO object at 0x0000013C023F5DF0>
res返回值的类型 <class 'NoneType'>
res结果 None
0: 416x416 1 1, 14.4ms
Traceback (most recent call last):
  File "D:\Progarm_Data\python_project\YOLOv8-multi-task-main\myCode\ImageDetection.py", line 21, in <module>
    annotated_img = res[0].plot()
                    ~~~^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by JiayuanWang-JW** [comment]
是的，目前这个存储库不支持视频和实时摄像头输入， 仅支持图像输入。
