### ISSUE TITLE
 evaluation

### ISSUE THREAD

**Issue by Wang2207** [JiayuanWang-JW/YOLOv8-multi-task#11]
The evaluation index of YOLOv8-seg in the paper contains mIoU, how to add mIoU in the source code.

**Comment by JiayuanWang-JW** [comment]
The official YOLOv8 source code uses ConfusionMatrix to calculate the metrics. In that class, it has the confusion matrix. Cite that to write a function to calculate the mIoU. Adding mIoU into metrics is not difficult to implement it.

**Comment by Wang2207** [comment]
Yes, I initially thought it wasn't difficult, but due to learning YOLO code at the beginning, there were always issues with adding mIoU code. I changed it for about two days, but there were still issues. Then I thought of your paper containing the mIoU indicator of YOLOv8 seg, so I would like to ask.
