### ISSUE TITLE
A question about the Segment Neck in model structure diagram in the paper.

### ISSUE THREAD

**Issue by ChunjieShan** [JiayuanWang-JW/YOLOv8-multi-task#15]
Hi!
I'm interested in the multi-task model architechture design in your paper very much, but I got confused that the _Segment Neck_ in your model architechture diagram does not seem to match your open source code in this repo. I've drawn a sketch based on my understanding. If I misunderstand your intention in your work, please correct me.

![A-YOLOM-explain](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/49755092/dc1ba253-e869-4091-b2c7-96c525332bf1)

**Comment by JiayuanWang-JW** [comment]
Hi

Thanks for carefully checking our code and manuscript. Yes, you are right. We made a mistake. We revised it, and we will update the manuscript in the next version. Sorry for any inconvenience. 

The algorithm follows the black line to implement. You don't need to care about the pyramid. We use only the last layer in segmentation tasks. 
![image](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/105391468/0a9e2114-baa3-4e47-a9ed-7936221cca38)

Thanks again.

**Comment by JiayuanWang-JW** [comment]
Hi

Thanks for carefully checking our code and manuscript. We revised it, and we will update the manuscript in the next version. Sorry for any inconvenience. 

The algorithm follows the black line to implement. You don't need to care about the pyramid. We use only the last layer in segmentation tasks. I hope this will help you to understand. 
![image](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/105391468/5db42a44-80cc-46c5-a173-6615d0a4b146)

**Comment by JiayuanWang-JW** [comment]
Hi

Thanks for carefully checking our code and manuscript. We revised it, and we will update the manuscript in the next version. Sorry for any inconvenience.

The algorithm follows the black line to implement. You don't need to care about the pyramid. We use only the last layer in segmentation tasks. I hope this will help you to understand.
![image](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/105391468/004c28ad-ec9a-4014-bac0-bbb99abbd71b)

Thanks again.
