### ISSUE TITLE
GPU mem is not stable

### ISSUE THREAD

**Issue by Zhangyongtao123** [JiayuanWang-JW/YOLOv8-multi-task#22]
hello, it's a very elegant work. I have some questions while I tried to reproduce your result:

1) When I tried to train BDD100k data, I found that the graphics memory usage was very unstable （eg: from 1G ~ 9G）. Is this normal?
![nvidia-smi_res](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/38833754/0e6f40c8-4fda-4110-880f-e1e79e16ed61)

2) I found that the prediction code for the BDD100Ks dataset you provided in read me requires an input size of 384x672, but  640x640 in training/validation code,  is it a writing mistake?

**Comment by XianYang2547** [comment]
2 不是，训练中一开始是640,好像在LetterBox中改变了

**Comment by JiayuanWang-JW** [comment]
1. Yes, it is normal. If you do not want dynamic memory. You can annotate the code [empty_cache](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/blob/cf1a1c433eebd32fcc3dd610a7eb745add9d361d/ultralytics/yolo/engine/trainer.py#L396C1-L396C41). Then GPU memory will be stable. I added it because my GPU memory is limited. If you have a large memory GPU, you can annotate this code.

**Comment by 2395268040** [comment]
请问只需要修改这一个地方吗？其他地方需不需要注释

**Comment by 2395268040** [comment]
> 1. Yes, it is normal. If you do not want dynamic memory. You can annotate the code [empty_cache](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/blob/cf1a1c433eebd32fcc3dd610a7eb745add9d361d/ultralytics/yolo/engine/trainer.py#L396C1-L396C41). Then GPU memory will be stable. I added it because my GPU memory is limited. If you have a large memory GPU, you can annotate this code. 

Excuse me, do you only need to modify this place? Do you need comments elsewhere?

**Comment by JiayuanWang-JW** [comment]
> > 1. Yes, it is normal. If you do not want dynamic memory. You can annotate the code [empty_cache](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/blob/cf1a1c433eebd32fcc3dd610a7eb745add9d361d/ultralytics/yolo/engine/trainer.py#L396C1-L396C41). Then GPU memory will be stable. I added it because my GPU memory is limited. If you have a large memory GPU, you can annotate this code.
> 
> Excuse me, do you only need to modify this place? Do you need comments elsewhere?

I think only modifying this place is fine for GPU memory.
