### ISSUE TITLE
Download links not working

### ISSUE THREAD

**Issue by kosmastsk** [JiayuanWang-JW/YOLOv8-multi-task#23]
Please update the download links, none of them are working.

Thanks :)

**Comment by JiayuanWang-JW** [comment]
Hi. Which link not works? I tried all download link are works.

**Comment by kosmastsk** [comment]
Actually none of the links on the uwin365-my.sharepoint.com domain, not the simple domain at all works.

Do you know if there are any limitations (location, etc?) or some other reason that might cause to not load this webpage?

**Comment by kosmastsk** [comment]
Alright, I'll try to figure it out and inform when I find the reason for that.
Thanks a lot, closing that issue :)
