### ISSUE TITLE
Question about displaying metrics during training

### ISSUE THREAD

**Issue by ZhanYeWei** [JiayuanWang-JW/YOLOv8-multi-task#26]
Thanks again for your help! The various parameters I have during training are shown below
![d84c34a08383ec9bc4bba4206b8dc79](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/72393610/4b132700-3160-4621-b3ed-8ab506ca706c)
One of the R, map50 doesn't seem to display properly, map50-95 doesn't seem to be quite right mIOU values don't seem to be quite right either, is this displaying correctly? If it is not correct, where should I change it, thank you for your help!

**Comment by JiayuanWang-JW** [comment]
Hi, I think your training looks good. You need to train more epochs. Only 8 is not enough. In my experiment. The same situation with you. The early epochs performance is not good, especially when I use a toy dataset to train. Because the samples of toy datasets are too few. 

Keep going and see what happens.

**Comment by ZhanYeWei** [comment]
> Hi, I think your training looks good. You need to train more epochs. Only 8 is not enough. In my experiment. The same situation with you. The early epochs performance is not good, especially when I use a toy dataset to train. Because the samples of toy datasets are too few.
> 
> Keep going and see what happens.

Thank you for your reply, after I forgot to take a screenshot at the last few epochs and had to take this graph as an example, I found that it seems that only the map50-95 values, P and R values among all are correct, and for each probe head these values are not quite right (e.g., IOU is <0.0001 all the time, pixacc is infinitely close to 1, and subacc is infinitely close to 0.5) Could you please tell me whether this is correct, thanks for your reply!
ps: I can train 100 epochs to show you the data if you want, thanks!

**Comment by JiayuanWang-JW** [comment]
In this case, all segmentation task results are incorrect. You need carefully to check the code. step by step to check each variable results. To see where is wrong. Debug is boring but necessary. 

Good luck and hope to hear your good news.

**Comment by ZhanYeWei** [comment]
> In this case, all segmentation task results are incorrect. You need carefully to check the code. step by step to check each variable results. To see where is wrong. Debug is boring but necessary.
> 
> Good luck and hope to hear your good news.

After our troubleshooting your code is fine, the reason for the problem is that the target we are detecting is too small in the image to use these metrics, thank you for your previous reply!

**Comment by YangBo0411** [comment]
I have encountered the same problem, have you resolved it?
