### ISSUE TITLE
Do this code has ONNX and Tensor RT support

### ISSUE THREAD

**Issue by Venkat-1405** [JiayuanWang-JW/YOLOv8-multi-task#28]
I have been trying to convert the pretrained model to onnx weight i cant achieve it . Is there any way to solve this issue

**Comment by JiayuanWang-JW** [comment]
I never tried this before. Unfortunately, I can not give any solution for that.

**Comment by PotatoNU** [comment]
Hello, I recently realized that this model was converted into onnx and accelerated by Tensor Rt, and it can be deployed to deepstream to run.

**Comment by loganwu0526** [comment]
hi, PotatuNU, 
do you know how to convert this multi-task model to .onnx (or .trt) and use it by TensorRT? I want to deploy this model in jetson device, thanks
