### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by China-Jervis** [JiayuanWang-JW/YOLOv8-multi-task#3]
How to solve the following problems？
WARNING 'YOLO' model does not support '_new' mode for 'multi' task yet.

**Comment by xuptly** [comment]
I have encountered the same problem and would like to ask how you resolved it?

**Comment by China-Jervis** [comment]
问题解决了，但是时间比较久了，忘记怎么解决的了。这里提供一种可能性，检查一下环境中是否安装了ultralytics，如果安装了，请先卸载，然后运行代码试试
