### ISSUE TITLE
det+line_seg

### ISSUE THREAD

**Issue by mengzhaoZ** [JiayuanWang-JW/YOLOv8-multi-task#30]
作者您好，这篇工作写的很好，请问如果我只想2D目标和车道线联合训练，请问需要如何修改参数

**Comment by JiayuanWang-JW** [comment]
Please read the README first, then you will easily implement your goal by changing some config files.

**Comment by mengzhaoZ** [comment]
您好，当我在运行程序时，出现了如下错误，请问是哪里出了问题。
![Uploading image.png…]()

**Comment by XianYang2547** [comment]
> 您好，当我在运行程序时，出现了如下错误，请问是哪里出了问题。 Traceback (most recent call last): File "ultralytics/train.py", line 12, in model.train(data='/home/zhangmz/project/YOLOv8-multi-task-main/ultralytics/datasets/bdd-multi.yaml', batch=1,imgsz=(640,640),name='v4_640', val=True, epochs=50, task='multi',classes=[2,3,4,9,10,11],combine_class=[2,3,4,9],single_cls=True) File "/home/zhangmz/project/YOLOv8-multi-task-main/ultralytics/yolo/engine/model.py", line 387, in train self.trainer.train() File "/home/zhangmz/project/YOLOv8-multi-task-main/ultralytics/yolo/engine/trainer.py", line 195, in train self._do_train(world_size) File "/home/zhangmz/project/YOLOv8-multi-task-main/ultralytics/yolo/engine/trainer.py", line 334, in _do_train for i, batch in pbar: File "/home/zhangmz/miniconda3/envs/yolov8_multi/lib/python3.7/site-packages/tqdm/std.py", line 1182, in **iter** for obj in iterable: File "/home/zhangmz/project/YOLOv8-multi-task-main/ultralytics/yolo/data/build.py", line 38, in **iter** yield next(self.iterator) File "/home/zhangmz/miniconda3/envs/yolov8_multi/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 652, in **next** data = self._next_data() File "/home/zhangmz/miniconda3/envs/yolov8_multi/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 692, in _next_data data = self._dataset_fetcher.fetch(index) # may raise StopIteration File "/home/zhangmz/miniconda3/envs/yolov8_multi/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/zhangmz/miniconda3/envs/yolov8_multi/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/zhangmz/project/YOLOv8-multi-task-main/ultralytics/yolo/data/base.py", line 282, in **getitem** transfer = self.transforms(label_list) File "/home/zhangmz/project/YOLOv8-multi-task-main/ultralytics/yolo/data/augment.py", line 56, in **call** data = t(data) File "/home/zhangmz/project/YOLOv8-multi-task-main/ultralytics/yolo/data/augment.py", line 56, in **call** data = t(data) File "/home/zhangmz/project/YOLOv8-multi-task-main/ultralytics/yolo/data/augment.py", line 108, in **call** tem_list = [file[count] for file in mix_labels] File "/home/zhangmz/project/YOLOv8-multi-task-main/ultralytics/yolo/data/augment.py", line 108, in tem_list = [file[count] for file in mix_labels] IndexError: list index out of range

106行处，for count in range(len(indexes)-1):  -1就行了，原来tem_list = [file[count] for file in mix_labels]中的file有三个元素,1个检测2个分割，如下            for i in range(len(self.data['labels_list'])):# labels_list': ['detection-object', 'seg-drivable-10', 'seg-lane-11'],，遍历了3次，而去掉一个分割任务的话，返回的file就只有两个长度，同时

**Comment by mengzhaoZ** [comment]
好的，谢谢，我试一下

**Comment by XianYang2547** [comment]
> 好的，谢谢，我试一下

可以加个联系方式，咱俩探讨一下威信Darling2547

**Comment by 2395268040** [comment]
感谢
