### ISSUE TITLE
Excuse me, I am having the following problem in use, how to solve it, thanks

### ISSUE THREAD

**Issue by 666abcljy** [JiayuanWang-JW/YOLOv8-multi-task#34]
![l](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/145779259/aa8446e9-3ee9-4804-acb5-9401bb2b86d7)

**Comment by JiayuanWang-JW** [comment]
Hi, please follow my instructions to set the parameter and implement the code because some functions I didn't extend to multi-task. That's why you received this error. However, you can change any code to implement what you want. 

It seems you are using classify albumentations augment. I think I didn't use it in my work.

**Comment by 666abcljy** [comment]
Thanks for the reply, after running the code again with your instructions, this issue still occurs. If you can please let me know how to make changes or where I have a problem with my settings. 
Or can I ignore the issue and will it have an impact on the results of my run.

**Comment by JiayuanWang-JW** [comment]
Please strictly follow my instructions except if you are familiar with the Yolov8 code and then you can DIY any function. Otherwise, you may get lots of errors and wrong results. 

I recommend you reproduce my work first. Then according to your task change the code. That will be easy to debug.

**Comment by YangBo0411** [comment]
> ![l](https://private-user-images.githubusercontent.com/145779259/300039629-aa8446e9-3ee9-4804-acb5-9401bb2b86d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mzg5ODEsIm5iZiI6MTcxMjgzODY4MSwicGF0aCI6Ii8xNDU3NzkyNTkvMzAwMDM5NjI5LWFhODQ0NmU5LTNlZTktNDgwNC1hY2I1LTk0MDFiYjJiODZkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxMjMxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTdhMGUyM2I4MzVkYjFiOGQ0NzhkYTI3MTRmYzQzMGUxMzBhODA3ZjgxZjVhMmJhYWNkYWJiOTQ0NGNhZDNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iKCjIgD-S6hGYdL5c1lt7_M70Zzby8IfgzLnkNJ33XY)
I have encountered the same problem. Have you resolved it?
