### ISSUE TITLE
own datasets

### ISSUE THREAD

**Issue by s0966066980** [JiayuanWang-JW/YOLOv8-multi-task#36]
Has anyone successfully used their own data set?
Currently using your own data set has the following problems

![螢幕快照 2024-02-20 18:28:05](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/45198905/173de297-428c-4c67-b3b5-98eb1bc33641)

The label box is incorrect,I use labelimg for labeling

![train_batchdetection-object0](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/45198905/d3cc004b-106d-4459-909b-94ab211989c1)

**Comment by 2395268040** [comment]
我也遇到这个问题

**Comment by JiayuanWang-JW** [comment]
Did you prepare the dataset following my dataset label? Could you provide your own dataset more details, please? I think the problem from data augment. In my mind, I changed some data augment parts to fit the multi-tasks.

**Comment by 2395268040** [comment]
> Did you prepare the dataset following my dataset label? Could you provide your own dataset more details, please? I think the problem from data augment. In my mind, I changed some data augment parts to fit the multi-tasks. 

Hello, resetting the data set according to your format requirements solved this problem.

**Comment by 2395268040** [comment]
> Did you prepare the dataset following my dataset label? Could you provide your own dataset more details, please? I think the problem from data augment. In my mind, I changed some data augment parts to fit the multi-tasks. ![image](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/75076392/6cb752c1-2eb8-4a25-ad80-63ca6116fb80)Hello, first of all, thank you very much for your work. According to your program configuration, why did you report this error? Is it the reason of data enhancement?

**Comment by JiayuanWang-JW** [comment]
> > Did you prepare the dataset following my dataset label? Could you provide your own dataset more details, please? I think the problem from data augment. In my mind, I changed some data augment parts to fit the multi-tasks. ![image](https://private-user-images.githubusercontent.com/75076392/312539884-6cb752c1-2eb8-4a25-ad80-63ca6116fb80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNzUwNzksIm5iZiI6MTcxMDM3NDc3OSwicGF0aCI6Ii83NTA3NjM5Mi8zMTI1Mzk4ODQtNmNiNzUyYzEtMmViOC00YTI1LWFkODAtNjNjYTYxMTZmYjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAwMDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MmQ5MWIxN2RkNWUyZjdmYWI0Mzg5MjMwYjM3ZmY2YWE3NjFiZTY0YTcyNjE4YTcyNTE4MDQyYzczYTJhZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C9jXUuZOGw5Ey5Kai0L3VmRi6fBwDDxn6e34jm2xiVk)Hello, first of all, thank you very much for your work. According to your program configuration, why did you report this error? Is it the reason of data enhancement?

I didn't report this error. I am not sure what you mean. Could give me more information about your question? I think you have successfully implemented the project with your dataset, right?

**Comment by 2395268040** [comment]
> > > Did you prepare the dataset following my dataset label? Could you provide your own dataset more details, please? I think the problem from data augment. In my mind, I changed some data augment parts to fit the multi-tasks. <img alt="image" width="54.141258239746094" height="20.998476028442383" src="https://private-user-images.githubusercontent.com/75076392/312539884-6cb752c1-2eb8-4a25-ad80-63ca6116fb80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNzUwNzksIm5iZiI6MTcxMDM3NDc3OSwicGF0aCI6Ii83NTA3NjM5Mi8zMTI1Mzk4ODQtNmNiNzUyYzEtMmViOC00YTI1LWFkODAtNjNjYTYxMTZmYjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAwMDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MmQ5MWIxN2RkNWUyZjdmYWI0Mzg5MjMwYjM3ZmY2YWE3NjFiZTY0YTcyNjE4YTcyNTE4MDQyYzczYTJhZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C9jXUuZOGw5Ey5Kai0L3VmRi6fBwDDxn6e34jm2xiVk">Hello, first of all, thank you very much for your work. According to your program configuration, why did you report this error? Is it the reason of data enhancement?您是否按照我的数据集标签准备了数据集？您能提供更多详细信息吗？我认为问题来自数据增强。在我的脑海中，我更改了一些数据增强部件以适应多任务。 <img alt="image" width="54.141258239746094" height="20.998476028442383" src="https://private-user-images.githubusercontent.com/75076392/312539884-6cb752c1-2eb8-4a25-ad80-63ca6116fb80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNzUwNzksIm5iZiI6MTcxMDM3NDc3OSwicGF0aCI6Ii83NTA3NjM5Mi8zMTI1Mzk4ODQtNmNiNzUyYzEtMmViOC00YTI1LWFkODAtNjNjYTYxMTZmYjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAwMDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MmQ5MWIxN2RkNWUyZjdmYWI0Mzg5MjMwYjM3ZmY2YWE3NjFiZTY0YTcyNjE4YTcyNTE4MDQyYzczYTJhZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C9jXUuZOGw5Ey5Kai0L3VmRi6fBwDDxn6e34jm2xiVk"> 您好，首先，非常感谢您的工作。根据您的程序配置，您为什么报告此错误？是数据增强的原因吗？
> 
> I didn't report this error. I am not sure what you mean. Could give me more information about your question? I think you have successfully implemented the project with your dataset, right?我没有报告此错误。我不确定你的意思。可以给我更多关于你的问题的信息吗？我认为您已经成功地用您的数据集实现了该项目，对吧？



> > > Did you prepare the dataset following my dataset label? Could you provide your own dataset more details, please? I think the problem from data augment. In my mind, I changed some data augment parts to fit the multi-tasks. <img alt="image" width="54.141258239746094" height="20.998476028442383" src="https://private-user-images.githubusercontent.com/75076392/312539884-6cb752c1-2eb8-4a25-ad80-63ca6116fb80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNzUwNzksIm5iZiI6MTcxMDM3NDc3OSwicGF0aCI6Ii83NTA3NjM5Mi8zMTI1Mzk4ODQtNmNiNzUyYzEtMmViOC00YTI1LWFkODAtNjNjYTYxMTZmYjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAwMDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MmQ5MWIxN2RkNWUyZjdmYWI0Mzg5MjMwYjM3ZmY2YWE3NjFiZTY0YTcyNjE4YTcyNTE4MDQyYzczYTJhZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C9jXUuZOGw5Ey5Kai0L3VmRi6fBwDDxn6e34jm2xiVk">Hello, first of all, thank you very much for your work. According to your program configuration, why did you report this error? Is it the reason of data enhancement?
> 
> I didn't report this error. I am not sure what you mean. Could give me more information about your question? I think you have successfully implemented the project with your dataset, right?

Thank you very much for your reply, I double-checked my dataset label file and there was a wrong label in it, and it was resolved after re-modifying the dataset label file!
![pycharm64_rvKBt3gX9V](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/75076392/f09936dc-5a1d-4d90-b0c2-c92a63e2b9eb)         Successfully run after modification!  
![pycharm64_dcbpg8CToJ](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/75076392/44e020c4-ea2e-49ca-8b74-2721fada5a80)
