### ISSUE TITLE
Why does the Adaptive Concatenation Module choose 0.5 as the threshold for sigmoid(weight)?

### ISSUE THREAD

**Issue by TonyMacedonia** [JiayuanWang-JW/YOLOv8-multi-task#37]
![Snipaste_2024-02-26_10-37-19](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/86862205/6de56fba-6527-4833-89a4-a91c33bc42eb)

**Comment by JiayuanWang-JW** [comment]
As consider this is a threshold. So you can set whatever you want. The learnable parameter is weight instead of this threshold. Maybe after tunning this threshold, the performance may be better than I report. Due to the resource limitation. I didn't based on my work fine-tune the parameters.
