### ISSUE TITLE
你好，我下载images的路径打不开：https://bdd-data.berkeley.edu/

### ISSUE THREAD

**Issue by mco0308** [JiayuanWang-JW/YOLOv8-multi-task#39]
<img width="377" alt="image" src="https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/132748106/e37d96c8-44e6-42aa-b463-ab8bb9c83986">

**Comment by 2395268040** [comment]
挂梯子🪜

**Comment by mco0308** [comment]
我挂了还是不行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月23日(周六) 凌晨0:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JiayuanWang-JW/YOLOv8-multi-task] 你好，我下载images的路径打不开：https://bdd-data.berkeley.edu/ (Issue #39)




 
挂梯子🪜

**Comment by 2395268040** [comment]
去官网下载，bdd100k

**Comment by mco0308** [comment]
您好，请问有具体的链接吗，我打开官网发现搜bdd100k发现有好多数据，我不知道下载哪个。😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月23日(周六) 凌晨0:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JiayuanWang-JW/YOLOv8-multi-task] 你好，我下载images的路径打不开：https://bdd-data.berkeley.edu/ (Issue #39)




 
去官网下载，bdd100k

**Comment by mco0308** [comment]
<img width="379" alt="image" src="https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/132748106/7d8c60c2-5e26-4a14-ba81-7a206d364118">

**Comment by Melody3377** [comment]
100k的test和val

**Comment by mco0308** [comment]
嗯嗯，我已经弄好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月6日(周六) 下午5:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JiayuanWang-JW/YOLOv8-multi-task] 你好，我下载images的路径打不开：https://bdd-data.berkeley.edu/ (Issue #39)




 
100k的test和val

**Comment by siit15** [comment]
你好请问是下载test和val吗

**Comment by mco0308** [comment]
不是，是train和test



---原始邮件---
发件人: "Wenrui ***@***.***&gt;
发送时间: 2024年4月7日(周日) 下午4:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JiayuanWang-JW/YOLOv8-multi-task] 你好，我下载images的路径打不开：https://bdd-data.berkeley.edu/ (Issue #39)




 
你好请问是下载test和val吗

**Comment by siit15** [comment]
> 不是，是train和test
> [...](#)
> ---原始邮件--- 发件人: "Wenrui ***@***.***&gt; 发送时间: 2024年4月7日(周日) 下午4:09 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [JiayuanWang-JW/YOLOv8-multi-task] 你好，我下载images的路径打不开：https://bdd-data.berkeley.edu/ (Issue #39) 你好请问是下载test和val吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

感谢

**Comment by AZong76** [comment]
> 不是，是train和test
> […](#)
> ---原始邮件--- 发件人: "Wenrui ***@***.***&gt; 发送时间: 2024年4月7日(周日) 下午4:09 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [JiayuanWang-JW/YOLOv8-multi-task] 你好，我下载images的路径打不开：https://bdd-data.berkeley.edu/ (Issue #39) 你好请问是下载test和val吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您好 可否留个联系方式  想向您询问一个小问题

**Comment by mco0308** [comment]
可以，这个是我qq:2448052777



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月29日(周六) 下午2:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JiayuanWang-JW/YOLOv8-multi-task] 你好，我下载images的路径打不开：https://bdd-data.berkeley.edu/ (Issue #39)




  
不是，是train和test
 …
 ---原始邮件--- 发件人: "Wenrui @.&gt; 发送时间: 2024年4月7日(周日) 下午4:09 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [JiayuanWang-JW/YOLOv8-multi-task] 你好，我下载images的路径打不开：https://bdd-data.berkeley.edu/ (Issue #39) 你好请问是下载test和val吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
您好 可否留个联系方式  想向您询问一个小问题
