### ISSUE TITLE
What is the format of segmented data？

### ISSUE THREAD

**Issue by Lacacy** [JiayuanWang-JW/YOLOv8-multi-task#4]
Can you easily display and explain it?

**Comment by JiayuanWang-JW** [comment]
Please follow [Segmentation format](https://docs.ultralytics.com/datasets/segment/) to prepare labels for segmentation tasks. That is Ultralytics YOLO format. We provide two examples, please download the [seg-drivable-10](https://uwin365-my.sharepoint.com/:u:/g/personal/wang621_uwindsor_ca/EWyIyXDFCzRLhERniUiuyIABq257WF4DbNJBDB8Dmok91w?e=hgWtoZ) or [seg-lane-11](https://uwin365-my.sharepoint.com/:u:/g/personal/wang621_uwindsor_ca/EUBQBO2KGFtHsexik3WvLZMBuaW1CsnHDTZo5eJ3ESdJNA?e=K6Tsem) to review.

**Comment by Lacacy** [comment]
thank you

**Comment by s0966066980** [comment]
> 請依照[分割格式](https://docs.ultralytics.com/datasets/segment/)為分割任務準備標籤。這就是 Ultralytics YOLO 格式。我們提供了兩個範例，請下載[seg-drive-10](https://uwin365-my.sharepoint.com/:u:/g/personal/wang621_uwindsor_ca/EWyIyXDFCzRLhERniUiuyIABq257WF4DbNJBDB8Dmok91w?e=hgWtoZ)或[seg-lane-11](https://uwin365-my.sharepoint.com/:u:/g/personal/wang621_uwindsor_ca/EUBQBO2KGFtHsexik3WvLZMBuaW1CsnHDTZo5eJ3ESdJNA?e=K6Tsem)進行查看。

How to convert json marked with labelme into files in seg-drivable-10 and seg-lane-11 formats
