### ISSUE TITLE
关于mIoU

### ISSUE THREAD

**Issue by YangBo0411** [JiayuanWang-JW/YOLOv8-multi-task#41]
作者您好，感谢你做出的杰出工作。关于代码有点疑惑，项目中进行训练和验证的分割数据集是以txt标注格式进行的，原始数据集是分割二值图的形式，以不同的标注形式计算得出的mIoU是否会存在差异。

**Comment by JiayuanWang-JW** [comment]
可以从mask转换到[YOLO格式](https://docs.ultralytics.com/datasets/segment/)的txt或者官方polygons格式转换成txt存储都可以的。BDD100k官方提供了不同的格式，不光二值图mask格式。我选择将mask转换成YOLO格式是因为想follow YOLOP的工作，这样方便对比性能，YOLOP用的BDD100k数据集是处理过的mask。

所以通过我给出的label计算出来的mIoU是符合YOLOP论文中处理后的BDD100k数据集，但是和官方的BDD100k有差异，因为YOLOP将lane两条线合并成了一条，并且像素大小也修改了，详情可以到YOLOP的论文去了解。我在论文中的所有对比方法都是遵循YOLOP的标注方式。
