### ISSUE TITLE
关于视频预测后保存问题

### ISSUE THREAD

**Issue by libaos** [JiayuanWang-JW/YOLOv8-multi-task#44]
![image](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/65326726/d2534fac-777f-470b-a1dc-36a318237cc2)
加入了save=True后会报错
![image](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/65326726/dbdaab4d-020e-459f-8c16-28ba72762524)

**Comment by JiayuanWang-JW** [comment]
This is because our code didn't support video format. We only support the images.
