### ISSUE TITLE
训练很慢是正常的吗？比常规的YOLOv8训练慢太多了，cache=True还是很慢

### ISSUE THREAD

**Issue by Tomhardy13** [JiayuanWang-JW/YOLOv8-multi-task#45]

**Comment by JiayuanWang-JW** [comment]
这是有可能，此库所有代码的修改都是我一个人完成的，多数修改都是用最简单的循环等方式，没有应用高级或高效的数据结构或处理方式，所以代码效率上肯定没法和YOLOv8官方大公司出品的相媲美。但我个人认为，修改的部分可读性和可修改性更好，官方代码一个功能很多都要跨越多个文件才能实现，而且函数复用也相当常见。我无法为了增加某一个功能去直接修改官方代码的函数，因为这样会导致其他地方复用逻辑出错。
