### ISSUE TITLE
This is wrong because I did not change Albumentations code for multi task

### ISSUE THREAD

**Issue by taotaoland** [JiayuanWang-JW/YOLOv8-multi-task#46]
The printed statement in the code "This is wrong because I did not change Albumentations code for multi task" means what?

**Comment by taotaoland** [comment]
How should I modify it?

**Comment by JiayuanWang-JW** [comment]
> The printed statement in the code "This is wrong because I did not change Albumentations code for multi task" means what?

For data augmentation, I didn't extend all functions to multi-task. That is why you receive this wrong information. 

However, you can extend other data augmentation functions by yourself. Good luck.

**Comment by taotaoland** [comment]
thank you
