### ISSUE TITLE
bdd-multi.yaml

### ISSUE THREAD

**Issue by taotaoland** [JiayuanWang-JW/YOLOv8-multi-task#47]
Excuse me, what does 'map: [None,{'10':'0'},{'11':'0'}]' in bdd-multi.yaml mean?

**Comment by qingtian787** [comment]
同问

**Comment by JiayuanWang-JW** [comment]
Hi @taotaoland , @qingtian787. I think you can ignore the 'map: [None,{'10':'0'},{'11':'0'}]' in bdd-multi.yaml now. This map is not useful now. I have annotate it in [trainer](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/blob/7a71c76f4eeef5215bed7d0d5909091bc1544296/ultralytics/yolo/engine/trainer.py#L337). I also annotate in [validator.py](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/blob/7a71c76f4eeef5215bed7d0d5909091bc1544296/ultralytics/yolo/engine/validator.py#L179). I insert the switch the seg labels functions into the preprocessing step. That will be more efficient than in the training step.
