### ISSUE TITLE
你好我想问下如果训练速度太慢是因为我的图片大小不是（720,1280）的问题么。

### ISSUE THREAD

**Issue by qingtian787** [JiayuanWang-JW/YOLOv8-multi-task#48]

**Comment by JiayuanWang-JW** [comment]
大概比官方的yolov8慢了多少？

**Comment by qingtian787** [comment]
慢了大概五倍

**Comment by qingtian787** [comment]
而且在predict的时候，只能输入1280*720大小的图片我想问下有什么解决方法么大佬

**Comment by JiayuanWang-JW** [comment]
5倍应该是合理的，我在测试n scale的时候用的1080Ti显卡，bs=1的时候大概慢3倍左右，bs=32的时候大概慢5倍左右。
由于使用了多个head和neck，所以慢一些是正常的， 而且我得数据处理也没有使用高级的数据结构和算法，所以综合下来可能会比YOLOv8稍慢，但是测试结果依然可以在1080Ti上FPS大于30，达到实时性。
我认为这个速度是正常的。因为我们一个模型同时实现了三个任务，在我得消融实验中也可以看到，我们的模型确实要比官方的yolov8 FPS低。

**Comment by qingtian787** [comment]
非常感谢

**Comment by yinheyanxian** [comment]
> 而且在predict的时候，只能输入1280*720大小的图片我想问下有什么解决方法么大佬

请问您解决这个问题了吗？

**Comment by qingtian787** [comment]
> > 而且在predict的时候，只能输入1280*720大小的图片我想问下有什么解决方法么大佬
> 
> 请问您解决这个问题了吗？

请问您解决这个问题了么大佬
