### ISSUE TITLE
我使用result=model.predict(source=input, device=[0],name='0516', save=True, conf=0.25, iou=0.45, show_labels=True)代码推理，但是返回值result没有结果，但是官方yolov8使用相同的result=model.predict 就有返回值，该处控制是否有返回值的代码在具体哪里啊

### ISSUE THREAD

**Issue by QiTianDaShengDaShi** [JiayuanWang-JW/YOLOv8-multi-task#50]
我使用result=model.predict(source=input, device=[0],name='0516', save=True, conf=0.25, iou=0.45, show_labels=True)代码推理，但是返回值result没有结果，但是官方yolov8使用相同的result=model.predict 就有返回值，该处控制是否有返回值的代码在具体哪里啊

**Comment by JiayuanWang-JW** [comment]
请按照[Prediction](https://github.com/JiayuanWang-JW/YOLOv8-multi-task?tab=readme-ov-file#prediction)去设置预测代码，此库并不完全兼容官方YOLOv8的操作命令及方式，尤其是最新版的YOLOv8。
