### ISSUE TITLE
可行驶区域

### ISSUE THREAD

**Issue by worlkingbling** [JiayuanWang-JW/YOLOv8-multi-task#51]
请问一下 我只想完成一个可行驶区域的任务 在 datasets 文件里选用 bdd-drivable-deg-toy对吗  在model 里面应该选用哪个yaml 文件啊

**Comment by JiayuanWang-JW** [comment]
那您需要根据您的任务去自定义一个新的yaml文件，因为模型的detection和另一个segmentation部分需要去掉，只保留一个segmentation部分即可。
对于dataset，您可以使用bdd-drivable-deg-toy。

**Comment by s0966066980** [comment]
請問如果使用bdd-drivable-deg-toy 該如何修改yolov8-bdd-v4-one-dropout-individual-n.yaml
