### ISSUE TITLE
目标检测类别有挺多，但是实际跑的时候只能检测车辆

### ISSUE THREAD

**Issue by QiTianDaShengDaShi** [JiayuanWang-JW/YOLOv8-multi-task#55]
博主，想问一下；
使用
```
      self.model = YOLO('./weights/v4s.pt')  # load a custom model

        english_name_dict = self.model.module.names if hasattr(self.model, 'module') else self.model.names
        self.english_name=list(english_name_dict.values())
        print("names=",self.english_name)
```
获取到检测类别有下面挺多的
names= ['person', 'rider', 'car', 'bus', 'truck', 'bike', 'motor', 'traffic light', 'traffic sign', 'train', 'drivable', 'lane']
但是实际跑的时候只能检测车辆，是什么原因吗？

**Comment by JiayuanWang-JW** [comment]
Hi @QiTianDaShengDaShi， 请提供详细的测试命令。

请注意，您应该把测试命令中的single_cls设置为了True，这样的话，所有检测类别都会被归为一类，因为YOLOP中将‘train’，‘car’，‘bus’，‘truck’视为一类去检测的，并且给出合并为一类后的mAP50检测指标，所以我们也增添了这个功能方便比较性能，如果您不需要将所有预测的类别合并为一类，请将single_cls设置为False。
请参阅readme中的详细信息去设置single_cls: This will combine whole detection classes into one class, for example, you have 7 classes in your dataset, and when you use "single_cls", it will automatically combine them into one class. When you set single_cls=False or delete the single_cls from model.train(). Please follow the below Note to change the "tnc" in both dataset.yaml and model.yaml, "nc_list" in dataset.yaml, the output of the detection head as well.
