### ISSUE TITLE
没有看到预训练模型呢

### ISSUE THREAD

**Issue by oyoanan** [JiayuanWang-JW/YOLOv8-multi-task#57]
您好，ultralytics/runs/best.pt文件并不在代码中，是在哪里下载呢？

**Comment by JiayuanWang-JW** [comment]
请下载[Pre-trained model](https://github.com/JiayuanWang-JW/YOLOv8-multi-task?tab=readme-ov-file#download)，然后替换，这个就是我训练后的models。

**Comment by oyoanan** [comment]
> 请下载[Pre-trained model](https://github.com/JiayuanWang-JW/YOLOv8-multi-task?tab=readme-ov-file#download)，然后替换，这个就是我训练后的models。

感谢！
