### ISSUE TITLE
论文中的实验数据

### ISSUE THREAD

**Issue by wofeifeileni** [JiayuanWang-JW/YOLOv8-multi-task#6]
您好，首先感谢您出色的工作以及开源代码。我注意到A-YOLOM论文中关于YOLOP的一些性能参数与其原论文中的数据不太一样，特别是车道线检测任务中的Accuracy指标，在YOLOP论文中只有70.50%，而A-YOLOM中给出的数据达到了84.8%，而且数据集同样都是BDD100k。这是如何做到的，是否是您重新对YOLOP训练并复现得到的结果，是否与验证时的参数设定有关

**Comment by JiayuanWang-JW** [comment]
Yes. We according to the YOLOP code reproduced the YOLOP and got results that were a little different from their paper. Some are better, some slightly worse. But for lane line segmentation accuracy, we adopt a balanced accuracy to calculate. We introduce this in our paper Section IV. A. 2). Please read it and you will understand. That is why we didn't display the "Enet", "SCNN", and "ENet-SAD" accuracy results. YOLOP reports the result has different metrics from ours.

**Comment by wofeifeileni** [comment]
明白了，感谢您的耐心解答。
