### ISSUE TITLE
为什么识别结果的标识都是"Person"

### ISSUE THREAD

**Issue by oyoanan** [JiayuanWang-JW/YOLOv8-multi-task#61]
不管改成识别什么，识别结果的标签都是"Person"。请问如何修改？

**Comment by JiayuanWang-JW** [comment]
Please read [train instruction](https://github.com/JiayuanWang-JW/YOLOv8-multi-task?tab=readme-ov-file#training) carefully, then you will find out why.

**Comment by oyoanan** [comment]
What is the map in bdd multi yaml ?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiayuanWang-JW/YOLOv8-multi-task"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月8日(星期六) 上午10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JiayuanWang-JW/YOLOv8-multi-task] 为什么识别结果的标识都是"Person" (Issue #61)





 
Please read train instruction carefully, then you will find out why.

**Comment by JiayuanWang-JW** [comment]
#62 希望这个答案可以帮助到你。
