### ISSUE TITLE
map: [None,{'10':'0'},{'11':'0'}]

### ISSUE THREAD

**Issue by oyoanan** [JiayuanWang-JW/YOLOv8-multi-task#62]
你好作者，我不理解这行代码map: [None,{'10':'0'},{'11':'0'}]的作用。另外，当我训练模型只识别红绿灯的时候，model.train(data='/home/Why/LaneProject/Code/YOLOv8-multi-task-main/ultralytics/datasets/bdd-multi.yaml', batch=32, epochs=10, imgsz=(640,640), device=[0,1], name='yolopm', val=True, task='multi',classes=[7,10,11],combine_class=[7],single_cls=True)。为什么识别结果的可视化图像上的label是person。经过调试发现，person来源于names[cls]，而每个box的cls都是0，如何解决？

**Comment by JiayuanWang-JW** [comment]
map: [None,{'10':'0'},{'11':'0'}]这个代码是我之前版本使用的，最新版本这行代码已经无用了，可以忽略掉。

为什么识别结果的可视化图像上的label是person。经过调试发现，person来源于names[cls]，而每个box的cls都是0，如何解决？
将single_cls=True设置为False就好了.
