### ISSUE TITLE
RuntimeError: The size of tensor a (8000) must match the size of tensor b (8400) at non-singleton dimension 1

### ISSUE THREAD

**Issue by 1402091247** [JiayuanWang-JW/YOLOv8-multi-task#64]
大佬你好，我用自己的数据集来训练，结果报出错误：RuntimeError: The size of tensor a (8000) must match the size of tensor b (8400) at non-singleton dimension 1

--train.py修改内容
 model.train(data='./datasets/bdd-multi.yaml', batch=16, epochs=300, imgsz=(640,640), device=[0], name='yolopm', val=True, task='multi',classes=[0,1,2,3],single_cls=True)
0，1，2是检测类别，3是分割类别

--bdd-multi.yaml修改内容：
labels_list:
  - det
  - seg

tnc: 4 # number of classes
nc_list: [3,1]
#map: [None,{'10':'0'},{'11':'0'}]

names:
  0: 0
  1: 1
  2: 2
  3: 3

--yolov8-bdd-v4-one-dropout-individual-n.yaml：只修改了tnc

请大佬答疑。

**Comment by JiayuanWang-JW** [comment]
你修改了分割任务类别数，所以[模型文件](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/blob/32824bb90542bcd6d24831eec7c9c911b40c181f/ultralytics/models/v8/yolov8-bdd-v4-one-dropout-individual-s.yaml)也要删掉一个head，不然还是一个detection head，两个segmentation heads，可能出问题的原因在这里。
