### ISSUE TITLE
关于收敛问题？

### ISSUE THREAD

**Issue by worlkingbling** [JiayuanWang-JW/YOLOv8-multi-task#66]
请问一下作者 您训练了多少轮开始趋向收敛的这个项目 ？  我复现的时候为什么在20轮左右就开始有收敛的趋势了，map miou 等参数开始趋向收敛了？

**Comment by JiayuanWang-JW** [comment]
训练前30轮的性能增长比较快，但是不代表完全收敛了，随着训练，map50和miou依然有增长，只是没那么快了。也就是从50轮到250轮map50和lane的IoU分别提高了2%左右。还是有增长的，所以模型没有早停。
