### ISSUE TITLE
The predic.py file only has detection and no segmentation

### ISSUE THREAD

**Issue by QHdsj1** [JiayuanWang-JW/YOLOv8-multi-task#7]
import sys
sys.path.insert(0, "/home/dsj/YOLOv8-multi-task/ultralytics")

from ultralytics import YOLO

number = 3 #input how many tasks in your work
model = YOLO('/home/dsj/YOLOv8-multi-task/runs/multi/yolopm3/weights/best.pt')  # Validate the model
model.predict(source='/media/dsj/260d5639-89a4-49ca-941b-e9bdc7443fb7/2D_datasets/dataset/BDD100K/BDDA/test/camera_videos/58.mp4', imgsz=(384,672), device=[1],name='output', box=True,save=True, conf=0.25, iou=0.45, show=False,)

**Comment by JiayuanWang-JW** [comment]
Our code does not support the video so far, only support detects and segments correctly for images. We will support video as input in the future. Thanks.
