### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by jasfa** [JiayuanWang-JW/YOLOv8-multi-task#70]
How to solve this problem?
File "YOLOv8-multi-task-main/ultralytics/yolo/utils/callbacks/tensorboard.py", line 17, in _log_scalars
    for k, v in scalars.items():
AttributeError: 'list' object has no attribute 'items'
python-BaseException

**Comment by jasfa** [comment]
When I run self.run_callbacks('on_fit_epoch_end'), the code reports an AttributeError.

def on_fit_epoch_end(trainer):
    """Logs epoch metrics at end of training epoch."""
    _log_scalars(trainer.metrics, trainer.epoch + 1)

Running trainer.metrics into this code results in the following:
![image](https://github.com/user-attachments/assets/5b079a2e-90d7-4c63-9ce2-caca573e92c6)

**Comment by jasfa** [comment]
But now The indicators in the detection part are all 0.
![Uploading image.png…]()

**Comment by JiayuanWang-JW** [comment]
Hi Jasfa,

Unfortunately, I didn't modify the code to fit the tensorboard. However, if you can handle this function, please create a pull request to help this repo better. Thanks!

Jiayuan

**Comment by zhang-pan** [comment]
How did you download the image data? I can't open the webpage when I click in

**Comment by jasfa** [comment]
> Hi Jasfa,
> 
> Unfortunately, I didn't modify the code to fit the tensorboard. However, if you can handle this function, please create a pull request to help this repo better. Thanks!
> 
> Jiayuan

Well, thank you all the same

**Comment by jasfa** [comment]
> How did you download the image data? I can't open the webpage when I click in

I downloaded it from another channel, but I can't remember where I downloaded it

**Comment by jasfa** [comment]
> How did you download the image data? I can't open the webpage when I click in

I downloaded it somewhere else, but I can't remember where
