### ISSUE TITLE
数据集制作细节

### ISSUE THREAD

**Issue by Miaonika** [JiayuanWang-JW/YOLOv8-multi-task#72]
请问您的数据集标签和BDD100k标签是怎么映射的，我今天分析可行驶区域 seg-drivable-10下的 label 和 BDD100k的 json label 没看出来两者间具体如何转换的？

**Comment by Miaonika** [comment]
How do you map your dataset label and BDD100k label, I didn't see how the two are converted when I analyzed the label under seg-drivable-10 and the JDSON label of BDD100k in the drivable area today?

**Comment by JiayuanWang-JW** [comment]
We reference [YOLOP's ](https://github.com/hustvl/YOLOP?tab=readme-ov-file#data-preparation)mask of segmentation task and change it to [YOLOv8 format](https://docs.ultralytics.com/datasets/segment/). More information on how to create the mask can be found on the YOLOP paper. They introduced it.
