### ISSUE TITLE
pixacc refers to

### ISSUE THREAD

**Issue by jasfa** [JiayuanWang-JW/YOLOv8-multi-task#74]
What do you refer to the two pixacc outputs in drivable and lane?
![image](https://github.com/user-attachments/assets/96a29450-dcdd-468c-a00f-0f19f758ef31)

**Comment by JiayuanWang-JW** [comment]
For drivable, we didn't use pixacc as the metics, just put it here. For lane line segmentation, we use subacc as ACC. Therefore, pixacc is not a contribution to this program.

**Comment by jasfa** [comment]
> For drivable, we didn't use pixacc as the metics, just put it here. For lane line segmentation, we use subacc as ACC. Therefore, pixacc is not a contribution to this program.

Thank you for your reply
