### ISSUE TITLE
关于分割指标IoU和mIoU的计算？

### ISSUE THREAD

**Issue by Cxgmg** [JiayuanWang-JW/YOLOv8-multi-task#78]
请问作者关于车道线和可行驶区域的计算指标IoU和mIoU中，他们的计算规则是怎么样的，是两个类别构成一个3*3的混淆矩阵进行计算还是每个类别在计算的时候只考虑自己（正例）和背景（反例)？因为我发现两个类别的mIoU并不一致，所以他们的计算是否是相互独立的，但如果是相互独立的情况下只有正反两类IoU和mIoU是否应该一致？

**Comment by JiayuanWang-JW** [comment]
每个类别在计算的时候只考虑自己，但是mIoU是考虑了前景+背景的，IoU只考虑了前景。

你可以研究一下代码[mIoU](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/blob/32824bb90542bcd6d24831eec7c9c911b40c181f/ultralytics/yolo/utils/metrics.py#L586)和[IoU](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/blob/32824bb90542bcd6d24831eec7c9c911b40c181f/ultralytics/yolo/utils/metrics.py#L598)的差别，这两个计算方式我是参考[YOLOP](https://github.com/hustvl/YOLOP/blob/8d8f68df318c71f01d6f813c024df646c7d1978f/lib/core/evaluate.py#L213)来写的。
