### ISSUE TITLE
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1080 but corresponding boolean dimension is 720

### ISSUE THREAD

**Issue by yinheyanxian** [JiayuanWang-JW/YOLOv8-multi-task#79]
Greetings.
I modified the code to be a detection task and a segmentation task, and it was successfully trained and tested. However, when I run predict.py, I get 'IndexError: boolean index did not match indexed array along dimension 0; dimension is 1080 but corresponding boolean dimension is 720 '.
My original image size was 1920×1080, but I changed the image size to 640×640 during training and testing, and no error was reported. I changed the image size to 640×640 when running predict.py, which didn't work. My original image size has not been changed, the weight size has also been changed to 720, what should I change?

**Comment by yinheyanxian** [comment]
Finished. Just change the size of the preprocessed image during segmentation.

**Comment by xsbrsg** [comment]
> Finished. Just change the size of the preprocessed image during segmentation.

请问您具体是怎么解决的呢？我用自己的数据训练，imgsz设置的（640， 640），预测的时候也报同样的错误
