### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by mengzhaoZ** [JiayuanWang-JW/YOLOv8-multi-task#8]
您好，我对您的工作十分感兴趣，想问下文章中所用的数据集是bdd中的哪一个，想要复现一下。谢谢！

**Comment by JiayuanWang-JW** [comment]
You just need to download the image from the BDD website. Then download the labels for each task I have provided under [Data preparation and Pre-trained model](https://github.com/JiayuanWang-JW/YOLOv8-multi-task#data-preparation-and-pre-trained-model). Good luck.

**Comment by mengzhaoZ** [comment]
当我训练时，出现了如下错误，请问需要怎么修改，已经按照readme进行配置
![image](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/84321799/672c725d-70f5-4a54-9389-7a265858c8be)

**Comment by mengzhaoZ** [comment]
您好，请问您在实验时，有没有将pt文件转为onnx呢，我在转onnx时出现了一点问题，想请教一下您。

**Comment by JiayuanWang-JW** [comment]
No. I didn't convert pt file to onnx.
