### ISSUE TITLE
There is an issue with the mask drawing obtained by running predict.by

### ISSUE THREAD

**Issue by yinheyanxian** [JiayuanWang-JW/YOLOv8-multi-task#80]
I modified my code to include a segmentation and a detection task, and ran predictability. py to get the results.
There is no problem with the detection result, but there is a problem with the segmentation result.
I have reviewed the results obtained during verification and found that the mask drawn during verification is correct. It seems that the predicted mask has moved forward as a whole.
Where should I modify it?

**Comment by yinheyanxian** [comment]
Finished.

**Comment by gp01pw** [comment]
HI @yinheyanxian I ran into same issue. Can you please share how you were able to resolve the issue?
