### ISSUE TITLE
predict返回为none

### ISSUE THREAD

**Issue by Fuheng188** [JiayuanWang-JW/YOLOv8-multi-task#86]
您好，感谢您做出的贡献。我在使用结果时，打印predict返回值是None。我也意识到您在predictor_multi.py里面删除了一个return，想请教一下您，如何修改呢，或者我现在一次只想取出结果里其中一个目标的mask数据，应该如何提取？

**Comment by JiayuanWang-JW** [comment]
“you should keep "det" in your detection tasks name and "seg" in your segmentation tasks name.”

我想您应该是在自己的数据集上出问题了吧？请按照上述准备您的数据集，一定要在文件中包含seg，否则是无法识别segmentation任务的，这样就不会打印任何segmentation的结果，det也一样。或者您需要提供更多的信息来找到问题。

**Comment by Fuheng188** [comment]
> “you should keep "det" in your detection tasks name and "seg" in your segmentation tasks name.”
> 
> 我想您应该是在自己的数据集上出问题了吧？请按照上述准备您的数据集，一定要在文件中包含seg，否则是无法识别segmentation任务的，这样就不会打印任何segmentation的结果，det也一样。或者您需要提供更多的信息来找到问题。

首先感谢您的热心回复，我的意思我在predict.py中print（model.predict），但打印的是None，原生的yolov8打印的是包含mask和class以及置信度信息的数组。尽管我的predict可视化结果实现了多任务，但提取不到数据信息。

**Comment by Fuheng188** [comment]
> “you should keep "det" in your detection tasks name and "seg" in your segmentation tasks name.”
> 
> 我想您应该是在自己的数据集上出问题了吧？请按照上述准备您的数据集，一定要在文件中包含seg，否则是无法识别segmentation任务的，这样就不会打印任何segmentation的结果，det也一样。或者您需要提供更多的信息来找到问题。

我对比了您predictor_multi.py和原生yolov8，发现您在后处理部分删除了一个return，导致不会返回封装好的mask box class 等信息，想请教一下您，应该如何修改呢

**Comment by JiayuanWang-JW** [comment]
是的，我这个代码不会返回mask box class信息，由于我将所有segmentation任务的object mask合并到了一个mask中，这个跟原始的yolov8实现方式不同，所以我当时并没有保留这个功能。[分割头](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/blob/main/ultralytics/nn/modules/head.py#L74)结构和逻辑是我自己写的，所以您提到的原始yolov8封装函数并不能适配我这个分割头，但是如果您把分割头改成原始yolov8的应该可以正常使用封装好的mask box class信息，但是计算acc，iou，miou以及可视化会出问题，您需要相应的一一修改文件，这将是个较大的工程。

**Comment by Fuheng188** [comment]
您好，我想您误会我的意思了。我明白您分割任务仅仅返回mask。我目前可以正确提取检测头里的任何信息包括box和class。我想从分割头里提取到mask，但我提取到的mask是一张图片中所有目标的mask，导致不能提取出单个目标的mask，并没有像原生v8一样将所有mask封装成一个nparry，我提取第几个元素就是第几个目标的mask，请问您应该如何修改一下。

**Comment by JiayuanWang-JW** [comment]
在我上一个回复中我提到了，我将所有segmentation任务的object mask合并到了一个mask中，这就是为什么您不能提取出单个目标的mask。具体来说[cv3](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/blob/32824bb90542bcd6d24831eec7c9c911b40c181f/ultralytics/nn/modules/head.py#L93)在预测的时候就把所有object合并成一个mask中了，只区分了背景和前景，并没有给出每一个object的mask，所以如果您想得到每一个object的单独mask信息，您需要重写分割头。

我的分割头执行的是Semantic Segmentation，而原始的yolov8执行的是Instance Segmentation。这是相当大的区别。

**Comment by CYJ-GH** [comment]
> 您好，我想您误会我的意思了。我明白您分割任务仅仅返回mask。我目前可以正确提取检测头里的任何信息包括box和class。我想从分割头里提取到mask，但我提取到的mask是一张图片中所有目标的mask，导致不能提取出单个目标的mask，并没有像原生v8一样将所有mask封装成一个nparry，我提取第几个元素就是第几个目标的mask，请问您应该如何修改一下。

想请教一下您是如何做到正确提取出检测头里包括box和mask在内的信息的呢？

**Comment by shiiang** [comment]
def write_results(self, idx, results_list, batch):
        """Write inference results to a file or directory."""

        # print(f"result idx{idx} batch{batch}")
 
        p, im, _ = batch
        log_string = ''
        if len(im.shape) == 3:
            im = im[None]  # expand for batch dim
        self.seen += 1
        if self.source_type.webcam or self.source_type.from_img:  # batch_size >= 1
            log_string += f'{idx}: '
            frame = self.dataset.count
        else:
            frame = getattr(self.dataset, 'frame', 0)
        self.data_path = p
        self.txt_path = str(self.save_dir / 'labels' / p.stem) + ('' if self.dataset.mode == 'image' else f'_{frame}')
        log_string += '%gx%g ' % im.shape[2:]  # print string
        plotted_img = []
        for i,results in enumerate(results_list):
            # print(f"i {i}")
            if isinstance(results,list):
                # print(f"i {i}")

                result = results[idx]

                boxes = result.boxes.xyxy  
                classes = result.boxes.cls 
                print(boxes.shape)
                print(classes)

这里拿到了但是类别为什么都是person用的是v4.pt
