### ISSUE TITLE
如何将两个分割头一个检测头换为两个检测头

### ISSUE THREAD

**Issue by lfn66** [JiayuanWang-JW/YOLOv8-multi-task#94]
你好，
我想了解下您多任务具体在原有的yolov8做了哪些改动来实现，目前我跟着在nn.task里的multibasemodel和multimodel进行了改动，以及将yaml文件进行了改动，还有哪些是需要改动来实现多任务的吗，我想将两个分割头去掉加上一个检测头，期待您的回答，谢谢

**Comment by JiayuanWang-JW** [comment]
数据处理部分改动比较大，主要是augment文件的各个增强函数逻辑需要支持多任务才可以。其他就是loss和结果输出部分也需要改动，包括画图。这些都完成就差不多了，但前提是你没有修改模型任何结构，只是增加了一个检测头。

**Comment by lfn66** [comment]
> 数据处理部分改动比较大，主要是augment文件的各个增强函数逻辑需要支持多任务才可以。其他就是loss和结果输出部分也需要改动，包括画图。这些都完成就差不多了，但前提是你没有修改模型任何结构，只是增加了一个检测头。

感谢回答，我研究研究
