### ISSUE TITLE
作者能否提供训练日志信息呢？想要和自己改进后的方法进行训练过程的对比。

### ISSUE THREAD

**Issue by yinheyanxian** [JiayuanWang-JW/YOLOv8-multi-task#97]

**Comment by JiayuanWang-JW** [comment]
这是[n scale](https://uwin365-my.sharepoint.com/:t:/g/personal/wang621_uwindsor_ca/Ea1xnYG5vJNKo3wxUmhFwL8B6BQ6RIx-l-pJHpmaBxHuBg?e=EUOgSL)的训练日志，文件很大，请下载查看。
请注意，分割任务性能指标在训练日志中没有任何问题，但是检测任务，请查看我们的论文说明 ”For evaluation, we set the confidence threshold at 0.001 and the Non-Maximum Suppression (NMS) threshold at 0.6.“ 我们参考了YOLOP项目的设置，所以在val代码中设置了不同的iou和conf参数，在训练中我们默认使用了YOLOv8的参数，所以结果有些不同，但是修改这些参数之后结果会是论文中所报告的结果，这个是[测试日志](https://uwin365-my.sharepoint.com/:t:/g/personal/wang621_uwindsor_ca/EUk2AzjzZuBKmg_nmIxdeJgBCPtyQhef1m7G_k2jEZ9N3A?e=KNInSH)。
关于参数量和FPS就像我在论文中介绍的一样，为了公平，我们reference了HybridNet去测试的，训练日志和测试日志都使用的YOLOv8标准。

**Comment by yinheyanxian** [comment]
> 这是[n scale](https://uwin365-my.sharepoint.com/:t:/g/personal/wang621_uwindsor_ca/Ea1xnYG5vJNKo3wxUmhFwL8B6BQ6RIx-l-pJHpmaBxHuBg?e=EUOgSL)的训练日志，文件很大，请下载查看。 请注意，分割任务性能指标在训练日志中没有任何问题，但是检测任务，请查看我们的论文说明 ”For evaluation, we set the confidence threshold at 0.001 and the Non-Maximum Suppression (NMS) threshold at 0.6.“ 我们参考了YOLOP项目的设置，所以在val代码中设置了不同的iou和conf参数，在训练中我们默认使用了YOLOv8的参数，所以结果有些不同，但是修改这些参数之后结果会是论文中所报告的结果，这个是[测试日志](https://uwin365-my.sharepoint.com/:t:/g/personal/wang621_uwindsor_ca/EUk2AzjzZuBKmg_nmIxdeJgBCPtyQhef1m7G_k2jEZ9N3A?e=KNInSH)。 关于参数量和FPS就像我在论文中介绍的一样，为了公平，我们reference了HybridNet去测试的，训练日志和测试日志都使用的YOLOv8标准。

感谢回复！您的研究十分有意义，我会持续关注。
