### ISSUE TITLE
你好！ 关于设置yamlfile，

### ISSUE THREAD

**Issue by Joungjimin** [JiayuanWang-JW/YOLOv8-multi-task#99]
我的计划
detection：label 0 
segmentation ： label 0 ， 1， 2 
single_cls: False

（检测的label0和分割的是一样的目标，所以在检测和分割的label数据都有0- 检测标注数据：0， 分割标注数据：0,1,2) 
这样的话，要怎么设置data.yaml呢？
（下面有要修改的吗）
而且，modelyaml的话要有几个head呢？（我写的是一个检测head和一个分割head）

1) data.yaml

labels_list: 
   detectection-labels-0
   seg-labels

tnc: 4  
nc_list: [1,3]

map:
   {'0': '0'}
   {'0': '0'}
   {'1': '1'}
   {'2': '2'}

names:
  0: q
  1: n
  2: z

2) model.yaml
![image](https://github.com/user-attachments/assets/785f63f4-bb09-4020-84ce-5645398e21f6)

**Comment by JiayuanWang-JW** [comment]
1. label 0涉及到了实例分割，并不是单纯的语义分割，实现实例分割需要改动数据处理部分的逻辑，这个库默认的是目标检测和语义分割，不支持实例分割。仅在data.yaml中是无法实现实例分割的。如果您想分开去做实例分割， 也就是把它当成检测+语义分割来做，也是可以的，只需要把label 0单独分出一个来给分割任务就可以了，命名的时候可以用detection_0, seg_0这种，这样加载数据的时候就可以按照您期望的检测+语义分割来执行。

2. 您在3个类别的分割任务中使用一个分割head是可行的，但需要您自行修改代码实现，目前这个代码库使用的是解耦式的分割头（n个分割任务采用n个分割头），因为这样可以最大限度地避免多任务之间的negative transfer。

**Comment by Joungjimin** [comment]
请问一下!
那么，可以将每个分割对象的标签分开，分别保存为3个标签并继续进行吗？
同时，也可以将head分成3个进行处理可以吗？
下面是按照这个想法写的，你可不可以帮我看有错的？


labels_list:
detectection-q-0 
seg-q-1
seg-n-2
seg-z-3

tnc: 4
nc_list: [1,1,1,1] 

map:
[????]
 

names:
0: q
1: q 
1: n
2: z

**Comment by JiayuanWang-JW** [comment]
可以的，那个map不用管，这个是之前遗留下来的变量，在之后的版本中，map已经不起作用了。

**Comment by Joungjimin** [comment]
感谢！

**Comment by Joungjimin** [comment]
你好！ 这样跑代码也分割没有什么preds结果
这样设置真的对吗

![image](https://github.com/user-attachments/assets/5bd40a11-ba8f-4273-9ad1-2483eefff1c2)

Preds shape: torch.Size([8, 672, 672])
Are all preds values False? tensor(True, device='cuda:0')
Are there any non-zero preds? tensor(False, device='cuda:0')
Preds shape: torch.Size([8, 672, 672])
Are all preds values False? tensor(True, device='cuda:0')
Are there any non-zero preds? tensor(False, device='cuda:0')
